package project;/*
 * This Java source file was generated by the Gradle 'init' task.
 */


/** The JavaFX application */
public class App{

    public static void main(String[] args) {
        System.out.println("111");
    }
}